### ISSUE TITLE
Build error using Node 20

### ISSUE THREAD

**Issue by wpplumber** [datalogix/google-fonts-helper#69]
The build was successful with Node 16 and after upgrade I got the following error:

```
$ node -r dotenv/config ./build-utils/generate-theme.mjs
node:fs:1210
  return handleErrorFromBinding(ctx);
         ^

Error: EINVAL: invalid argument, rmdir './'
    at rmdirSync (node:fs:1210:10)
    at _rmdirSync (node:internal/fs/rimraf:235:5)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1259:10)
    at Downloader.execute (file:///Users/fork/node_modules/google-fonts-helper/dist/index.mjs:177:7)
    at generateFontFiles (file:///Users/fork/build-utils/fonts-node.mjs:21:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -22,
  syscall: 'rmdir',
  code: 'EINVAL',
  path: './'
}

Node.js v20.9.0
```

**Comment by ricardogobbosouza** [comment]
Hi @wpplumber 
Which version are you using?
Are you sure the error is in this library?

**Comment by wpplumber** [comment]
It is `3.3.1`.

After commenting the lines below it works. (seems an issue with rmSync)

```
 if (overwriting) {
    rmSync(outputDir, { recursive: true, force: true });
   }
```
